title: Sadler Farms LLC
tagline: A New Vision for Lakeside Living
description: >-
  Sadler Farms: 300 acres with about a mile of waterfront on Lake Wheeler
  and the Tennessee River in Limestone County, Alabama.
url: "https://sadlerfarmsllc.com"
email: info@sadlerfarmsllc.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Files/dirs to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .github
  - tools
  - assets/photos
  - assets/videos
  - assets/audio
  - assets/concepts
  - assets/site-plans
